# Generated by Django 3.1.5 on 2022-11-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('quantity', models.SmallIntegerField()),
                ('status', models.BooleanField()),
                ('Image', models.ImageField(upload_to='')),
            ],
        ),
    ]
